### ISSUE TITLE
Update WP Background Processing Library to latest version

### ISSUE THREAD

**Issue by remyperona** [JulioPotier/secupress#62]
The currently used version in SP is missing the `cancel_process()` method, that we are using in WP Rocket since 2.11.

Since SP is loaded before WP Rocket in the admin, it's the WPBP version included in SP that is loaded (since the library is wrapped with `class_exists()` checks).

This could also affect WooCommerce who are also using the library in some cases.

**Comment by JulioPotier** [comment]
Fixed in 1.4.
#SEC-577
