### ISSUE TITLE
Please, feel free to "Steal" features from my WAF!

### ISSUE THREAD

**Issue by szepeviktor** [JulioPotier/secupress#64]
It has 60+ security checks but no UI, and intended for hosting professionals.
https://github.com/szepeviktor/wordpress-fail2ban

All my knowledge of HTTP and WordPress is in it!

**Comment by JulioPotier** [comment]
Hello Viktor

What's the point, I don't understand the issue.
The title is saying "steal", then you're linking your github account etc

Can you explain the issue maybe? Thank you

**Comment by szepeviktor** [comment]
I would welcome any of the 60 checks in Secupress. That's it.

**Comment by szepeviktor** [comment]
@BoiteAWeb Before beginning to develop it I was contributing to very popular - so called - security plugins like Better WP Security and Sucuri Scan. Later I've realized that analyzing HTTP traffic is the only way to develop a proper WAF.

**Comment by JulioPotier** [comment]
Ho, ok lol. You want me to "steal" your work.
Ok, I'll have a look and if I add any of your work, it won't be stolen, it's GPL and open source, you'll be mentioned.
Don't blame me if I don't do that quickly ;)

Big thanks Viktor!
