### ISSUE TITLE
Delete outdated branches

### ISSUE THREAD

**Issue by Seldaek** [JulioPotier/secupress#65]
You have old branches like `fix/SEC-667-cron-HS-Fatal-error-Uncaught-Error-Call-to-undefined-function-secupress_scanit()-in-/secupress-pro/inc/modules/schedules/plugins/inc/php/class-secupress-background-process-schedules-scan.php-47` which are super long and fail to be saved as they max out the character limit on packagist.org - failing the package update repeatedly.

**Comment by JulioPotier** [comment]
Hello

My bad I didn't know about the length limit, how much is it?
I'll clean that.

Thank you

**Comment by Seldaek** [comment]
The DB column stores only 255 chars for the version field, so when truncation occurs it bails out.

**Comment by JulioPotier** [comment]
Ok thanks! I cleaned it up all the things ;)
