### ISSUE TITLE
Salt scanning question

### ISSUE THREAD

**Issue by mjdewitt** [JulioPotier/secupress#76]
My site, is being penalized for having some salt keys stored in the DB:

The following security keys are not set correctly:
· From DB: secure_auth_key and secure_auth_salt.

I'm not sure why this would matter after having passed the other salt tests (not default values and not defined in wp-config)?

The DB salts seem to be a WP failsafe for times when no salt is defined.  According to https://developer.wordpress.org/reference/functions/wp_salt/ , " The secret key in the database is randomly generated and will be appended to the secret keys in wp-config.php." This suggests to me that the DB salts are inconsequential unless no salt key is already defined.

My belief is that the DB salt key test should only be run if no salt key is defined and it exists in the DB.

But, then again, maybe I am misunderstanding the nature of the DB test?

Last, I very much appreciate all of the tests you have put together. I run down every "bad" finding to see if this something that I should change or not.

Mike

**Comment by JulioPotier** [comment]
This is a support question, not a code issue.
